Respect whitespace in scope filenames

diff --git a/utils/0mp-explore b/utils/0mp-explore
--- a/utils/0mp-explore
+++ b/utils/0mp-explore
@@ -30,7 +30,7 @@
 # SUCH DAMAGE.
 
 program='0mp-explore'
-version=0.14.2
+version=1.0.0
 
 bold='\033[1m'
 nobold='\033[0m'
@@ -153,7 +153,7 @@ done
 EOF
     )"
 
-    find ${scope:-'.'} \( -type f -o -type l \) -name "${regex:-*}" \
+    find "${@:-.}" \( -type f -o -type l \) -name "${regex:-*}" \
         -exec sh -c "$script" sh {} + 2>/dev/null | \
         less --no-init --chop-long-lines --RAW-CONTROL-CHARS --ignore-case
 }
@@ -231,63 +231,16 @@ parse_opt_stdin() {
     done
 }
 
-# Parameters:
-# $@ - Arguments to be parsed.
-# Environmental variables:
-# - colors
-# - leftbar
-# - leftbarseparator
-# - regex
-# - scope
-parse() {
-    while [ $# -gt 0 ]
-    do
-        case $1 in
-            --ascii|-A) parse_opt_ascii ;;
-            --colors|-c) parse_opt_colors ;;
-            --shorthelp|-h) parse_opt_shorthelp ;;
-            --help) parse_opt_help ;;
-            --names|-n) parse_opt_names ;;
-            --nonumbers|-N) parse_opt_nonumbers ;;
-            --regex|-r) parse_opt_regex "${2?missing regex}"; shift ;;
-            --version) parse_opt_version ;;
-            --wildcards|-w) parse_opt_wildcards "${2?missing regex}"; shift ;;
-            --stdin|-) parse_opt_stdin ;;
-            --)
-                shift
-                if [ $# -gt 0 ]
-                then
-                    scope="${scope:-""} $@"
-                fi
-                break
-                ;;
-            -*)
-                # String of short options glued together, e.g., '-Acw'.
-                opts="${1#-}"
-
-                while [ @@ != "@$opts@" ]
-                do
-                    opt="${opts%%"${opts#?}"}"
-                    case $opt in
-                        A) parse_opt_ascii ;;
-                        c) parse_opt_colors ;;
-                        h) parse_opt_shorthelp ;;
-                        n) parse_opt_names ;;
-                        N) parse_opt_nonumbers ;;
-                        r) shift; parse_opt_regex "${1?missing regex}" ;;
-                        w) shift; parse_opt_wildcards "${1?missing regex}" ;;
-                        -) parse_opt_stdin ;;
-                        *) ;;
-                    esac
-                    opts="${opts#"$opt"}"
-                done
-                ;;
-            *)
-                scope="${scope:-""} $1"
-                ;;
-        esac
-        shift
-    done
+# Avoid filenames starting with a dash in find paths.
+# https://stackoverflow.com/a/4286196/4694621
+# "$1" - Argument to dotslashify.
+dotslashify() {
+    if [ "@${1%"${1#?}"}@" = '@-@' ]
+    then
+        printf '%s' "./$1"
+    else
+        printf '%s' "$1"
+    fi
 }
 
 colors=
@@ -296,10 +249,91 @@ leftbarseparator='█'
 regex=
 scope=
 
-parse $_0MP_EXPLORE_OPTS
-parse "$@"
+state=''
+for arg in $_0MP_EXPLORE_OPTS "$@"
+do
+    if [ -z "$state" ]
+    then
+        set --
+        state=0
+    fi
 
-scope="${scope# }"
+    case $state in
+        1)
+            state=0
+            ;;
+        --regex)
+            parse_opt_regex "$arg"
+            state=0
+            ;;
+        --wildcards)
+            parse_opt_wildcards "$arg"
+            state=0
+            ;;
+        skip)
+            set -- "$@" "$(dotslashify "$arg")"
+            ;;
+        0)
+            case $arg in
+                -A|--ascii) parse_opt_ascii ;;
+                -c|--colors) parse_opt_colors ;;
+                -h|--shorthelp) parse_opt_shorthelp ;;
+                -n|--names) parse_opt_names ;;
+                -N|--nonumbers) parse_opt_nonumbers ;;
+                -r|--regex) state=--regex ;;
+                -w|--wildcards) state=--wildcards ;;
+                -|--stdin) parse_opt_stdin ;;
+                --help) parse_opt_help ;;
+                --version) parse_opt_version ;;
+                --) state=skip ;;
+                -*)
+                    # String of short options glued together, e.g., '-Acw'.
+                    opts="${arg#-}"
+
+                    while [ @@ != "@$opts@" ]
+                    do
+                        opt="${opts%%"${opts#?}"}"
+                        case $opt in
+                            A) parse_opt_ascii ;;
+                            c) parse_opt_colors ;;
+                            h) parse_opt_shorthelp ;;
+                            n) parse_opt_names ;;
+                            N) parse_opt_nonumbers ;;
+                            # --regex and --wildcards are mutually exclusive so
+                            # we only remember the last state.
+                            r) state=--regex ;;
+                            w) state=--wildcards ;;
+                            -) parse_opt_stdin ;;
+                            *) ;;
+                        esac
+                        opts="${opts#"$opt"}"
+                    done
+                    ;;
+                *)
+                    set -- "$@" "$(dotslashify "$arg")"
+                    ;;
+            esac
+            ;;
+        *)
+            echo 'invalid state reached during parsing of command line arguments' >&2
+            ;;
+    esac
+done
+
+# Make sure that we got all the arguments we need.
+case $state in
+    --regex|--wildcards)
+        echo 'missing regex' >&2
+        exit 1
+        ;;
+    *) ;;
+esac
+
+# Append files from SCOPE to find paths.
+for scope in $SCOPE
+do
+    set -- "$@" "$(dotslashify "$scope")"
+done
 
 if [ "@$colors@" = @yes@ ]
 then
@@ -307,4 +341,4 @@ then
 else
     command='cat --'
 fi
-explore
+explore "$@"
