Fix battery-alert

diff --git a/home/.local/bin/battery-alert b/home/.local/bin/battery-alert
--- a/home/.local/bin/battery-alert
+++ b/home/.local/bin/battery-alert
@@ -1,21 +1,18 @@
 #! /bin/sh -
 
-run_battery_alert() {
-threshold_file="${HOME}/.0mp-switch/battery-alert-threshold"
-alert_off_file="${HOME}/.0mp-switch/battery-alert-off"
-threshold=15
+threshold_file="${HOME}/.cache/battery-alert-threshold"
+alert_off_file="${HOME}/.cache/battery-alert-off"
+threshold="15"
 
-if [ ! -e "${alert_off_file}" ] && [ -e "${threshold_file}" ]
-then
-    new_threshold="$(cat -- "${threshold_file}")"
-    case ${new_threshold} in
-    [0-9][0-9]*)
-        threshold="${new_threshold}"
-        ;;
-    esac
-fi
+printinfo() {
+    printf 'INFO: %s\n' "$*" >&2
+}
 
-battery_dies() {
+printerr() {
+    printf 'ERROR: %s\n' "$*" >&2
+}
+
+battery_charged() {
     acpiconf -i "$1" | awk -v discharging=no -v threshold="${threshold}" '
         /^State:[[:space:]]+discharging$/ {
             discharging = yes
@@ -25,30 +22,16 @@ battery_dies() {
         }
         END {
             if (int(capacity) < int(threshold)) {
-                exit 0
+                exit 1
             }
-            exit 1
+            exit 0
         }'
 }
-if [ -e "${alert_off_file}" ]
-then
-    exit 0
-fi
 
-# Is it running low on power?
-for battery in $( seq 0 "$(( $( sysctl -n hw.acpi.battery.units ) - 1 ))" )
-do
-    if battery_dies "${battery}"
-    then
-        continue
-    else
-        exit 0
-    fi
-done
-
-touch -- "${alert_off_file}"
-button="ALRIGHT I'M ON IT JUST PLEASE DON'T DIE OK?"
-xmessage -buttons "${button}" -default "${button}" -file - <<'MESSAGE'
+set_alarm_off() {
+    touch -- "${alert_off_file}"
+    button="ALRIGHT I'M ON IT JUST PLEASE DON'T DIE OK?"
+    xmessage -buttons "${button}" -default "${button}" -file - <<'MESSAGE'
  _   _ _____ _     _     ___    _____ _   _ _____ ____  _____ _
 | | | | ____| |   | |   / _ \  |_   _| | | | ____|  _ \| ____| |
 | |_| |  _| | |   | |  | | | |   | | | |_| |  _| | |_) |  _| | |
@@ -93,7 +76,43 @@ xmessage -buttons "${button}" -default "${button}" -file - <<'MESSAGE'
 MESSAGE
 }
 
-acpiconf -i0 >/dev/null || exit 0
-while run_battery_alert; do
-    sleep 2
+if [ -e "${alert_off_file}" ]; then
+    printinfo "Alert is off, exiting"
+    exit 0
+fi
+
+if ! acpiconf -i0 >/dev/null; then
+    printinfo "ACPI does not report presence of any battery systems; exiting"
+    exit 0
+fi
+
+if [ -e "${threshold_file}" ]; then
+    new_threshold="$(cat -- "${threshold_file}")"
+    case ${new_threshold} in
+    [0-9]|[1-9][0-9]|100)
+        threshold="${new_threshold}"
+        ;;
+    *)
+        printerr "Invalid threshold in threshold file: $new_threshold"
+        exit 1
+        ;;
+    esac
+fi
+
+if ! battery_units="$(( $( sysctl -n hw.acpi.battery.units ) - 1 ))"; then
+    printerr "Failed to obtain number of battery units"
+    exit 1
+fi
+
+while :; do
+    sleep 10
+    for battery in $(seq 0 "$battery_units")
+    do
+        if battery_charged "${battery}"
+        then
+            continue 2
+        fi
+        set_alarm_off
+        exit 0
+    done
 done
