Make require() error message a bit more specific

diff --git a/essential/dh_local/d_bin/s_n0tes b/essential/dh_local/d_bin/s_n0tes
--- a/essential/dh_local/d_bin/s_n0tes
+++ b/essential/dh_local/d_bin/s_n0tes
@@ -134,7 +134,7 @@ END
 BEGIN sh_require
 require() {
 	if ! command -v "$1" >/dev/null; then
-		printf "%s\n" "ERROR: Command not found: $1" >&2
+		printf "%s\n" "ERROR: Dependency not found: $1" >&2
 		exit 1
 	fi
 }
