Use require() in user daemons

diff --git a/freebsd-home/dh_local/d_bin/s_eyes-alert b/freebsd-home/dh_local/d_bin/s_eyes-alert
--- a/freebsd-home/dh_local/d_bin/s_eyes-alert
+++ b/freebsd-home/dh_local/d_bin/s_eyes-alert
@@ -1,6 +1,15 @@
 #! /bin/sh -
 #
-# Version 1.0
+# Version 1.1
+
+require() {
+	if ! command -v "$1" >/dev/null; then
+		printf "%s\n" "ERROR: Command not found: $1" >&2
+		exit 1
+	fi
+}
+
+require notify-send
 
 pause="$((60 * 15))"
 
diff --git a/freebsd-home/dh_local/d_bin/s_pie-menu b/freebsd-home/dh_local/d_bin/s_pie-menu
--- a/freebsd-home/dh_local/d_bin/s_pie-menu
+++ b/freebsd-home/dh_local/d_bin/s_pie-menu
@@ -1,5 +1,12 @@
 #! /bin/sh -
 
+require() {
+	if ! command -v "$1" >/dev/null; then
+		printf "%s\n" "ERROR: Dependency not found: $1" >&2
+		exit 1
+	fi
+}
+
 loop() {
 	items="
 IMG:/usr/local/share/pixmaps/firefox.png	firefox
@@ -8,6 +15,9 @@ IMG:/home/0mp/Downloads/lock.png			slock
 "
 	printf '%s\t%s\n' $items | pmenu | nohup sh >/dev/null 3>&1
 }
+
+require pmenu
+require xclickroot
 
 if [ "$1" = "loop" ]; then
 	loop
